function! StripWhitespace ()
  exec ':%s/\s\+$//'
endfunction
noremap <leader>ss :call StripWhitespace ()<CR>

set gfn=Menlo\ Regular:h13
setglobal rnu

inoremap jk <ESC>

" Use ctrl-[hjkl] to Select the active split!
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" test
